name: Ha Duy Trung
url: https://hidroh.github.io
description: Tips and tricks, useful patterns and implementations for Android
author: Ha Duy Trung
keywords: Android, Technical blog, Java, hidroh, Materialistic, Ha Duy Trung

permalink: /:year/:month/:day/:title/
paginate: 5
highlighter: rouge
excerpt_separator: <!--more-->

gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'CNAME']