name: A lil' bit of programming that matters
url: http://hidroh.github.io
description: Tips and tricks, useful patterns and implementations for Android

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']