name: A lil' bit of programming that matters
url: http://hidroh.github.io
description: Tips and tricks, useful patterns and implementations for Android
author: Ha Duy Trung
keywords: Android, Technical blog, Java, hidroh, Materialistic, Ha Duy Trung

permalink: /:year/:month/:day/:title/
paginate: 2
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']